### ISSUE TITLE
Feature: Support for printing/exporting Mo in JSON format

### ISSUE THREAD

**Issue by vvb** [CiscoUcs/ucsmsdk#72]
Today a managed object is returned as a python dictionary, we have `__str__` methods on the ManagedObject class that lets us print it as `key:value`. It would be nice to be able to dump an MO in the JSON format.

**Comment by vesposito** [comment]
I believe this has been fixed with commit 3569a7c31cb7fb9bbd8209c7f283438cf53feb32 related to issue #147 

I can now dump an MO in JSON format:
mo = handle.query_dn("fabric/san")
print(mo.__json__())

{'class_id': 'FabricSanCloud', 'child_action': None, 'dn': 'fabric/san', 'fsm_descr': '', 'fsm_prev': 'SwitchModeSuccess', 'fsm_progr': '100', 'fsm_rmt_inv_err_code': 'none', 'fsm_rmt_inv_err_descr': '', 'fsm_rmt_inv_rslt': '', 'fsm_stage_descr': '', 'fsm_stamp': '2017-08-31T22:48:17.982', 'fsm_status': 'nop', 'fsm_try': '0', 'mode': 'end-host', 'rn': 'san', 'sacl': None, 'status': None}
