### ISSUE TITLE
Error launching UCSM GUI - Windows 8

### ISSUE THREAD

**Issue by jasonsha** [CiscoUcs/ucsmsdk#96]
Windows 8, logged in as user assigned to Administrator Group
- Java 1.8.0_91-b15
- Python 2.7.11

UCSM GUI launches properly from PowerTool and from Chrome Browser

> > > from ucsmsdk.ucshandle import UcsHandle
> > > handle = UcsHandle("198.18.133.91","admin","passsword",secure=False)
> > > handle.login()
> > > True
> > > from ucsmsdk.utils.ucsguilaunch import ucs_gui_launch
> > > ucs_gui_launch(handle)
> > > 2016-07-27 04:31:23,289 - ucs - DEBUG - AuthToken: <78971976973711969313511>
> > > 2016-07-27 04:31:23,302 - ucs - DEBUG - UCSM URL: http://198.18.133.91:80/ucsm/ucsm.jnlp?ucsmToken=78971976973711969313511
> > > 2016-07-27 04:31:23,306 - ucs - DEBUG - Not able to access registry.
> > > 2016-07-27 04:31:23,309 - ucs - DEBUG - Not able to access registry.

```
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    ucs_gui_launch(handle)
  File "C:\Python27\lib\site-packages\ucsmsdk\utils\ucsguilaunch.py", line 117, in ucs_gui_launch
    if os.path.exists(jnlp_file):
  File "C:\Python27\lib\genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
>>> 
```

**Comment by vvb** [comment]
@jasonsha 

Thanks for reporting the issue.

There is an issue with accessing windows registry here. There seems to be some OS specific logic here. This logic will kick-in to detect Java install path.

To workaround it for now, you can set `JAVA_HOME` environment variable in Windows, and it should work. You will have to quit the shell and relaunch the cmd prompt after setting the environment variable.

Please let me know how it goes, while I work on resolving the issue.

**Comment by jasonsha** [comment]
Thanks Vikrant!  The workaround is working.

- Jason

**Comment by interop-hcl** [comment]
Hi Vikrant,

I have Cisco UCSMSDK library installed and I am trying to use convert_to_python utility to get the ucs scripts based on my actions in Java GUI. 
I am getting an error when doing ucs_gui_launch(handle)
TypeError: coercing to Unicode: need string or buffer, NoneType found
![ucs_gui](https://user-images.githubusercontent.com/26954334/28823416-0bda3b12-76db-11e7-9e32-c07a2b7be8dd.png)

I have JAVA_HOME environment variable set properly.

Convert to python was previously working fine.I have upgraded UCS Manager to 3.1(3a) and noticed that "Beginning with Cisco UCS Manager Release 3.1(3a), the Cisco UCS Manager GUI is no longer available as a Java-based application"(From release notes).

Is the above error because of no Java based GUI in latest UCS 3.1(3a)? If so how do I workaround and get to use convert_to_python ?
Please advice as  this is an urgent request.
Please find attached screenshot

Thanks,
Janani

**Comment by kami-nashi** [comment]
Its a year later, but this is also the case with RHEL:

```
2017-09-16 18:24:16,570 - ucs - DEBUG - AuthToken: <06838215085980879692031>
2017-09-16 18:24:16,570 - ucs - DEBUG - UCSM URL: <https://192.168.100.142:443/ucsm/ucsm.jnlp?ucsmToken=06838215085980879692031>
Traceback (most recent call last):
  File "ucs_starter", line 35, in <module>
    ucs_gui()
  File "ucs_starter", line 33, in ucs_gui
    ucs_gui_launch(handle)
  File "/usr/lib/python2.7/site-packages/ucsmsdk/utils/ucsguilaunch.py", line 117, in ucs_gui_launch
    if os.path.exists(jnlp_file):
  File "/usr/lib64/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

My JAVA_HOME is set correctly. I can launch a KVM session with similar code.
